plugin-prefix: "&b[&7SafeDrops&b]"

messages:
  drop: "Drop again within {amount} seconds to drop your items!"

# These items must be confirmed to be dropped
whitelist:
- "DIAMOND_BLOCK"


# in seconds
droptime: 3